version: '2'
services:
  jhipsterblogsample-app:
    image: jhipsterblogsample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterblogsample-mysql:3306/jhipsterblogsample?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  jhipsterblogsample-mysql:
    extends:
      file: mysql.yml
      service: jhipsterblogsample-mysql
